spring:
  application:
    name: j-booking
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    schemas: booking
    locations: classpath:db/migration
    baseline-on-migrate: true # Базовый уровень, если база не пуста
    #spring.flyway.clean-disabled=false   # временно для dev
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      acks: all
    consumer:
      auto-offset-reset: earliest
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  cache:
    type: redis
app:
  services:
    transaction-api:
      url: "http://217.29.121.129/bank_api/api/v1/transactions"