CREATE SEQUENCE IF NOT EXISTS address_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS address_id_seq1 START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS booking_records_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS booking_records_id_seq1 START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS clients_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS clients_id_seq1 START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS hotels_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS hotels_id_seq1 START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS rooms_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE address
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    country         VARCHAR(255),
    city            VARCHAR(255),
    street          VARCHAR(255),
    building_number VARCHAR(255),
    CONSTRAINT pk_address PRIMARY KEY (id)
);

CREATE TABLE booking_records
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    room_id   BIGINT,
    check_in  date,
    check_out date,
    CONSTRAINT pk_booking_records PRIMARY KEY (id)
);

CREATE TABLE clients
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255),
    surname VARCHAR(255),
    CONSTRAINT pk_clients PRIMARY KEY (id)
);

CREATE TABLE hotels
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255),
    address_id    BIGINT,
    building_type VARCHAR(255),
    CONSTRAINT pk_hotels PRIMARY KEY (id)
);

CREATE TABLE rooms
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    hotel_id      BIGINT,
    room_class    VARCHAR(255),
    room_capacity VARCHAR(255),
    CONSTRAINT pk_rooms PRIMARY KEY (id)
);

ALTER TABLE hotels
    ADD CONSTRAINT uc_hotels_address UNIQUE (address_id);

ALTER TABLE booking_records
    ADD CONSTRAINT fk_booking_records_on_room FOREIGN KEY (room_id) REFERENCES rooms (id) ON DELETE NO ACTION;

ALTER TABLE hotels
    ADD CONSTRAINT fk_hotels_on_address FOREIGN KEY (address_id) REFERENCES address (id) ON DELETE NO ACTION;

ALTER TABLE rooms
    ADD CONSTRAINT fk_rooms_on_hotel FOREIGN KEY (hotel_id) REFERENCES hotels (id) ON DELETE NO ACTION;