CREATE TABLE address
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    country         VARCHAR(255),
    city            VARCHAR(255),
    street          VARCHAR(255),
    building_number VARCHAR(255),
    CONSTRAINT pk_address PRIMARY KEY (id)
);

CREATE TABLE hotels
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255),
    address_id    BIGINT,
    building_type VARCHAR(255),
    check_in      date,
    check_out     date,
    room          DOUBLE PRECISION,
    CONSTRAINT pk_hotels PRIMARY KEY (id)
);

ALTER TABLE hotels
    ADD CONSTRAINT FK_HOTELS_ON_ADDRESS FOREIGN KEY (address_id) REFERENCES address (id);