version: '3.8'
services:
  db:
    image: postgres:16-alpine # Используем легкий и актуальный образ PostgreSQL
    container_name: j_booking # Порт для доступа к базе данных
    # 5432 — стандартный порт PostgreSQL
    ports:
      - "5432:5432"
    environment:
    # --- Обязательные учетные данные и имя БД ---
    # Замените эти значения на ваши:
      POSTGRES_DB: "postgres" # Имя базы данных, которая будет создана
      POSTGRES_USER: "postgres" # Имя суперпользователя
      POSTGRES_PASSWORD: "postgres" # Пароль для суперпользователя # Отключение ведения журнала (для тестовых сред)
      # PGDATA: /var/lib/postgresql/data/pgdata # Сохранение данных в томе (для постоянства)
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Политика перезапуска
    restart: always


  redis:
    image: redis:7.2-alpine # Легкий и актуальный образ Redis
    container_name: redis_server # Открываем стандартный порт Redis 6379
    ports:
      - "6379:6379"
#    command: redis-server --requirepass secure_redis_pass --appendonly yes
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: always


  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest
    container_name: redis_commander_ui
    environment:
      REDIS_HOSTS: "local_redis:redis:6379"
      REDIS_PASSWORD: "secure_redis_pass" # Имя, которое будет отображаться в интерфейсе
      REDIS_CLUSTERS: "default"
    ports: # Открываем порт для веб-интерфейса (например, 8086)
      - "8086:8086"
    depends_on:
      - redis
    restart: always
volumes:
  postgres_data:
  redis_data: